### ISSUE TITLE
[Question] How could I visit the website like you did in GIF?

### ISSUE THREAD

**Issue by Quorafind** [elias-sundqvist/obsidian-static-file-server#3]
Is the `www.desmos.com/caculator.html` a file in your path? Or I missed something?

**Comment by elias-sundqvist** [comment]
Yes, I have a single folder which I call "Offline Proxy", and I have put several different folders there, one for each website that I want to access offline. 
![image](https://user-images.githubusercontent.com/9102856/121407667-da829880-c95f-11eb-9852-ba7047fb0f1c.png)

I used the [Save All Resources chrome extension](https://chrome.google.com/webstore/detail/save-all-resources/abpdnfjocnmdomablahdcfnoggeeiedb). to download the website. 

If you map the port (say, 1234) directly to the www.desmos.com folder, it should work out of the box. 
Then you can simply write `src="http://localhost:1234/calculator.html"` in your iframe tag.

If you want to put websites in subfolders, like I did, it is a bit trickier. Many links will break, and some websites won't work at all. 
My fix in the case of desmos was to change all absolute links to relative links. (By doing a replace all from `="/` to `="./`) in `calculator.html`

**Comment by Quorafind** [comment]
Thanks for tons of tips. Maybe you could add this to the README, so that people could understand how you did it.
